### ISSUE TITLE
More dropdown menu shenanigans

### ISSUE THREAD

**Issue by xiaat** [enkoder/beanstalk#19]
If you set your filters in such a fashion that the leaderboard returns 0 results, and then click a filter, the dropdown menus are cut off by some invisible box. It also creates a scroll bar to navigate this box. :)
![78](https://github.com/enkoder/beanstalk/assets/133262510/9422a605-bbab-4db8-8621-596e48818876)

**Comment by enkoder** [comment]
Thanks for reporting the issue @xiaat! Fixed
