### ISSUE TITLE
[Suggestion] Remember the last filters used, or setting a default filter

### ISSUE THREAD

**Issue by xiaat** [enkoder/beanstalk#20]
What I'd like to have is some way to set default filters for when I open the website. For example I'm most interested in the current season data and that's what I'd like to see straight away, other people may have other preferences. I can see this being a setting in the profile section, or just saving your last choice via cookies.

**Comment by enkoder** [comment]
Taking a simple approach on this one and just setting the season to be the current one when nothing is selected.
