### ISSUE TITLE
Filters don't reset after returning to main page

### ISSUE THREAD

**Issue by xiaat** [enkoder/beanstalk#21]
If you set up some filters, and then click on "Beanstalk" in the top left corner, it correctly returns you to the main page, but doesn't reset the filter fields, although they're not active anymore.  
![566](https://github.com/enkoder/beanstalk/assets/133262510/31245f71-723d-4566-b69e-4c3fabd95098)

**Comment by enkoder** [comment]
Thanks for the report @xiaat!! Should be fixed now
